title: OCILIB (C and C++ Driver for Oracle) - Open source C and C++ library for accessing Oracle databases 
email: vince.rogier@ocilib.net

keywords: OCILIB, driver, Oracle, OCI, wrapper, open source, C, C++, library, API, SQL, database, access, libraries, free, Apache 2, PL/SQL, Oracle Call Interface
description: OCILIB is an open source and cross platform Oracle Driver that delivers efficient access to Oracle databases. It offers a full featured, easy and productive API. Written in ISO C and C++ on top of OCI, OCILIB runs on all Oracle platforms.

baseurl: /ocilib
url: / #Leave this, change the baseurl.

projecturl: https://github.com/vrogier/ocilib
meurl: https://github.com/vrogier/

header: yes
header_img: images/ocilib-header.png

exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]
 
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

destination: _site

permalink: /blog/:year/:title

google_universal_analytics: UA-64388697-1
google_universal_analytics_cookiedomain: auto

twitter_user: ocilib
twitter_card: true
twitter_image: 

ocilib_current_release_version: 4.7.2
ocilib_current_release_date: 2020-11-10
ocilib_author: Vincent Rogier